# Generated by Django 5.1.7 on 2025-03-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='cost',
            new_name='amount_allocated',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='item',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='paid',
        ),
        migrations.AddField(
            model_name='budget',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
