# Generated by Django 5.1.7 on 2025-03-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_rename_cost_budget_amount_allocated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
