# Generated by Django 5.1.7 on 2025-03-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_task_options_remove_task_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assigned To'),
        ),
    ]
