# Generated by Django 5.1.7 on 2025-03-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_budgetsettings_totalbudget_alter_budget_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetSettings',
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='totalbudget',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='totalbudget',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
