# Generated by Django 5.1.7 on 2025-03-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_delete_budgetsettings_alter_budget_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totalbudget',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
