# Generated by Django 5.1.7 on 2025-03-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_budget_amount_paid_alter_totalbudget_total_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalBudget',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='amount_paid',
        ),
    ]
