# Generated by Django 5.1.7 on 2025-03-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_totalbudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalbudget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
