# Generated by Django 5.1.7 on 2025-03-25 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_totalbudget_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='table_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
